"use client";
import { ChangeEvent, useEffect, useState } from "react";
import { createPortal } from "react-dom";
import * as XLSX from "xlsx";
import { catalogApi } from "./catalog-api";

const columns=["platform_product_id","canonical_slug","name","short_description","description_long","category_l1","category_l2","brand","currency","tax_percent","selling_price","mrp","rating","inventory_qty","stock_status","is_active","unit","unit_value","barcode","featured_score","color_hex","supplier_user_id","image_url"] as const;
type Row=Partial<Record<(typeof columns)[number],string|number|boolean>>;
const required=["platform_product_id","canonical_slug","name","category_l1","selling_price","mrp","unit"] as const;

function mapRow(row:Row,index:number):Record<string,unknown>{
 for(const field of required)if(row[field]===undefined||row[field]===null||row[field]==="")throw new Error(`Row ${index+2}: ${field} is required.`);
 const numeric=(field:keyof Row,fallback=0)=>{const value=Number(row[field]??fallback);if(!Number.isFinite(value))throw new Error(`Row ${index+2}: ${field} must be a valid number.`);return value};
 return {platform_product_id:String(row.platform_product_id).trim(),canonical_slug:String(row.canonical_slug).trim(),name:String(row.name).trim(),short_description:row.short_description?String(row.short_description):null,description_long:row.description_long?String(row.description_long):null,category_l1:String(row.category_l1).trim(),category_l2:row.category_l2?String(row.category_l2).trim():null,brand:row.brand?String(row.brand).trim():null,currency:String(row.currency||"INR").toUpperCase(),tax_percent:numeric("tax_percent"),selling_price:numeric("selling_price"),mrp:numeric("mrp"),rating:numeric("rating"),inventory_qty:numeric("inventory_qty"),stock_status:String(row.stock_status||"in_stock"),is_active:!(row.is_active===false||String(row.is_active).toLowerCase()==="false"),unit:String(row.unit).trim(),unit_value:numeric("unit_value",1),barcode:row.barcode?String(row.barcode).trim():null,featured_score:numeric("featured_score"),color_hex:row.color_hex?String(row.color_hex).trim():null,supplier_user_id:row.supplier_user_id?String(row.supplier_user_id).trim():null,image_url:row.image_url?String(row.image_url).trim():null};
}

export default function ProductImportWidget(){
 const [target,setTarget]=useState<Element|null>(null),[open,setOpen]=useState(false),[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{const timer=setTimeout(()=>setTarget(document.querySelector(".product-actions")),0);return()=>clearTimeout(timer)},[]);
 const sample=()=>{const row={platform_product_id:"PLAT-0001",canonical_slug:"sample-product",name:"Sample Product",short_description:"Short summary",description_long:"Full product description",category_l1:"Grocery",category_l2:"Snacks",brand:"Sample Brand",currency:"INR",tax_percent:5,selling_price:95,mrp:100,rating:4.5,inventory_qty:25,stock_status:"in_stock",is_active:true,unit:"pcs",unit_value:1,barcode:"890000000001",featured_score:10,color_hex:"",supplier_user_id:"SUP-001",image_url:"https://example.com/product.jpg"};const sheet=XLSX.utils.json_to_sheet([row],{header:[...columns]});const book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,sheet,"Products");XLSX.writeFile(book,"platform-product-import-sample.xlsx")};
 const run=async()=>{if(!file)return setMessage("Choose an Excel file first.");setBusy(true);setMessage("");try{const book=XLSX.read(await file.arrayBuffer());const sheet=book.Sheets[book.SheetNames[0]];const rows=XLSX.utils.sheet_to_json<Row>(sheet,{defval:""});if(!rows.length)throw new Error("The spreadsheet has no product rows.");const products=rows.map(mapRow);const result=await catalogApi.importProducts(products);setMessage(`Import complete: ${result.created} created, ${result.updated} updated, ${result.unchanged} unchanged.`);setTimeout(()=>location.reload(),1000)}catch(reason){setMessage(`${reason instanceof Error?reason.message:"Import failed."} No rows were saved.`)}finally{setBusy(false)}};
 return <>{target&&createPortal(<button className="primary-button excel-import-trigger" onClick={()=>setOpen(true)}>↑ Import</button>,target)}{open&&createPortal(<div className="import-overlay"><div className="import-modal"><header><h2>Import Products</h2><button onClick={()=>setOpen(false)}>×</button></header><div className="import-body"><div className="import-label"><strong>Import Excel File</strong><button onClick={sample}>⇩ Sample File</button></div><label className="excel-file"><span>Choose File</span><em>{file?.name??"No file chosen"}</em><input type="file" accept=".xlsx,.xls" onChange={(event:ChangeEvent<HTMLInputElement>)=>setFile(event.target.files?.[0]??null)}/></label><p className="import-atomic-note">All rows are saved together. If one row fails, the complete import is rolled back.</p>{message&&<p className="import-message">{message}</p>}</div><footer><button className="primary-button" disabled={busy} onClick={run}>{busy?"Validating & importing...":"Import"}</button><button className="secondary-button" disabled={busy} onClick={()=>setOpen(false)}>Close</button></footer></div></div>,document.body)}</>;
}
