"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { catalogApi } from "./catalog-api";
import type { CatalogEntity } from "./types";
import { confirmToast } from "../notifications";

export default function UnitManager(){
 const [items,setItems]=useState<CatalogEntity[]>([]),[search,setSearch]=useState(""),[status,setStatus]=useState("");
 const [name,setName]=useState(""),[editing,setEditing]=useState<CatalogEntity|null>(null),[showModal,setShowModal]=useState(false);
 const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{setItems(await catalogApi.entities("units",search,status));}catch(e){setError(e instanceof Error?e.message:"Could not load units");}finally{setLoading(false)}},[search,status]);
 useEffect(()=>{const timer=setTimeout(()=>void load(),250);return()=>clearTimeout(timer)},[load]);
 const close=useCallback(()=>{setShowModal(false);setEditing(null);setName("")},[]);
 useEffect(()=>{if(!showModal)return;const escape=(e:KeyboardEvent)=>{if(e.key==="Escape")close()};document.addEventListener("keydown",escape);return()=>document.removeEventListener("keydown",escape)},[showModal,close]);
 const openCreate=()=>{setEditing(null);setName("");setShowModal(true)};
 const openEdit=(item:CatalogEntity)=>{setEditing(item);setName(item.name);setShowModal(true)};
 const submit=async(e:FormEvent)=>{e.preventDefault();if(name.trim().length<1)return;setSaving(true);setError("");try{const payload={name:name.trim(),active:editing?.active??true};if(editing)await catalogApi.updateEntity("units",editing.id,payload);else await catalogApi.createEntity("units",payload);close();await load()}catch(reason){setError(reason instanceof Error?reason.message:"Could not save unit")}finally{setSaving(false)}};
 const remove=async(item:CatalogEntity)=>{if(!(await confirmToast(`Delete ${item.name}?`)))return;try{await catalogApi.deleteEntity("units",item.id);await load()}catch(reason){setError(reason instanceof Error?reason.message:"Could not delete unit")}};
 return <div className="catalog-admin-page variant-page unit-page">{error&&<div className="api-notice">{error}<button onClick={()=>setError("")}>×</button></div>}<section className="variant-header"><h1>All Units</h1><div className="variant-header-actions"><label className="variant-search"><span>⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search units"/></label><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All Status</option><option value="true">Active</option><option value="false">Inactive</option></select><button className="variant-add-button" onClick={openCreate}><span>＋</span>Add Unit</button></div></section><section className="variant-table-card"><table className="variant-table unit-table"><thead><tr><th>S/L</th><th>Unit Name</th><th>Status</th><th>Action</th></tr></thead><tbody>{loading?<tr><td colSpan={4}>Loading...</td></tr>:items.length===0?<tr><td colSpan={4}><div className="table-state"><strong>No units found</strong></div></td></tr>:items.map((item,index)=><tr key={item.id}><td data-label="No.">{index+1}</td><td data-label="Unit"><div className="variant-name"><span>{item.name[0].toUpperCase()}</span><strong>{item.name}</strong></div></td><td data-label="Status"><button type="button" className={`switch ${item.active?"on":""}`} onClick={async()=>{await catalogApi.toggleEntity("units",item.id);await load()}} aria-label={`Toggle ${item.name}`}><i/></button><span className="variant-status-text">{item.active?"Active":"Inactive"}</span></td><td data-label="Actions"><div className="row-actions"><button className="row-action edit" onClick={()=>openEdit(item)}>Edit</button><button className="row-action delete" onClick={()=>void remove(item)}>Delete</button></div></td></tr>)}</tbody></table></section>{showModal&&<div className="variant-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><section className="variant-modal" role="dialog" aria-modal="true"><header><h2>{editing?"Edit Unit":"Add Unit"}</h2><button type="button" onClick={close}>×</button></header><form onSubmit={submit}><div className="variant-modal-body"><label htmlFor="unit-name">Unit Name <b>*</b></label><input id="unit-name" autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. kg, g, litre, piece"/><small>Enter the measurement label displayed with product quantities.</small></div><footer><button type="button" className="variant-cancel-button" onClick={close}>Cancel</button><button className="variant-save-button" disabled={saving||!name.trim()}><span>✓</span>{saving?"Saving...":editing?"Update Unit":"Save Unit"}</button></footer></form></section></div>}</div>;
}
