"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { catalogApi } from "./catalog-api";
import type { CatalogEntity } from "./types";
import { confirmToast } from "../notifications";

export default function VariantManager(){
 const [items,setItems]=useState<CatalogEntity[]>([]),[search,setSearch]=useState(""),[status,setStatus]=useState("");
 const [name,setName]=useState(""),[editing,setEditing]=useState<CatalogEntity|null>(null),[showModal,setShowModal]=useState(false);
 const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{setItems(await catalogApi.entities("variations",search,status));}catch(e){setError(e instanceof Error?e.message:"Could not load variants");}finally{setLoading(false);}},[search,status]);
 useEffect(()=>{const timer=setTimeout(()=>void load(),250);return()=>clearTimeout(timer);},[load]);
 const closeModal=useCallback(()=>{setShowModal(false);setEditing(null);setName("");},[]);
 useEffect(()=>{if(!showModal)return;const close=(event:KeyboardEvent)=>{if(event.key==="Escape")closeModal()};document.addEventListener("keydown",close);return()=>document.removeEventListener("keydown",close);},[showModal,closeModal]);
 const openCreate=()=>{setEditing(null);setName("");setShowModal(true);};
 const openEdit=(item:CatalogEntity)=>{setEditing(item);setName(item.name);setShowModal(true);};
 const submit=async(e:FormEvent)=>{e.preventDefault();if(name.trim().length<2)return;setSaving(true);setError("");try{const payload={name:name.trim(),active:editing?.active??true};if(editing)await catalogApi.updateEntity("variations",editing.id,payload);else await catalogApi.createEntity("variations",payload);closeModal();await load();}catch(reason){setError(reason instanceof Error?reason.message:"Could not save variant");}finally{setSaving(false);}};
 const remove=async(item:CatalogEntity)=>{if(!(await confirmToast(`Delete ${item.name}?`)))return;try{await catalogApi.deleteEntity("variations",item.id);await load();}catch(reason){setError(reason instanceof Error?reason.message:"Could not delete variant");}};
 return <div className="catalog-admin-page variant-page">{error&&<div className="api-notice">{error}<button onClick={()=>setError("")}>×</button></div>}<section className="variant-header"><h1>All Variants</h1><div className="variant-header-actions"><label className="variant-search"><span>⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search variants"/></label><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All Status</option><option value="true">Active</option><option value="false">Inactive</option></select><button className="variant-add-button" onClick={openCreate}><span>＋</span>Add Variant</button></div></section><section className="variant-table-card"><table className="variant-table"><thead><tr><th>S/L</th><th>Variant Name</th><th>Status</th><th>Action</th></tr></thead><tbody>{loading?<tr><td colSpan={4}>Loading...</td></tr>:items.length===0?<tr><td colSpan={4}><div className="table-state"><strong>No variants found</strong></div></td></tr>:items.map((item,index)=><tr key={item.id}><td data-label="No.">{index+1}</td><td data-label="Variant"><div className="variant-name"><span>{item.name[0].toUpperCase()}</span><strong>{item.name}</strong></div></td><td data-label="Status"><button type="button" className={`switch ${item.active?"on":""}`} onClick={async()=>{await catalogApi.toggleEntity("variations",item.id);await load();}} aria-label={`Toggle ${item.name}`}><i/></button><span className="variant-status-text">{item.active?"Active":"Inactive"}</span></td><td data-label="Actions"><div className="row-actions"><button className="row-action edit" onClick={()=>openEdit(item)}>Edit</button><button className="row-action delete" onClick={()=>void remove(item)}>Delete</button></div></td></tr>)}</tbody></table></section>{showModal&&<div className="variant-modal-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)closeModal()}}><section className="variant-modal" role="dialog" aria-modal="true" aria-labelledby="variant-modal-title"><header><h2 id="variant-modal-title">{editing?"Edit Variant":"Add Variant"}</h2><button type="button" onClick={closeModal} aria-label="Close">×</button></header><form onSubmit={submit}><div className="variant-modal-body"><label htmlFor="variant-name">Variant Name <b>*</b></label><input id="variant-name" autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Size, Color, Weight"/><small>Use a clear name that can be selected while creating products.</small></div><footer><button type="button" className="variant-cancel-button" onClick={closeModal}>Cancel</button><button className="variant-save-button" disabled={saving||name.trim().length<2}><span>✓</span>{saving?"Saving...":editing?"Update Variant":"Save Variant"}</button></footer></form></section></div>}</div>;
}
