"use client";

import { useState } from "react";
import type { Category } from "./types";

type Props={categories:Category[];loading:boolean;search:string;onSearchChange:(v:string)=>void;onAdd:()=>void;onEdit:(c:Category)=>void;onDelete:(c:Category)=>void};
type TableProps={title:string;items:Category[];level:"L1"|"L2";loading:boolean;onEdit:(c:Category)=>void;onDelete:(c:Category)=>void};

function CategoryTable({items,level,loading,onEdit,onDelete}:TableProps){
 return <section className="category-table-card category-level-table"><div className="category-table-scroll"><table className="category-table"><thead><tr><th>S/L</th><th>{level==="L1"?"Main Category":"Subcategory"}</th>{level==="L2"&&<th>L1 Main Category</th>}<th>Products</th><th>Priority</th><th>Updated</th><th>Action</th></tr></thead><tbody>{loading?<tr className="state-row"><td colSpan={level==="L2"?7:6}>Loading...</td></tr>:items.length===0?<tr className="state-row"><td colSpan={level==="L2"?7:6}><div className="table-state"><strong>No {level} categories found</strong></div></td></tr>:items.map((item,index)=><tr key={item.id}><td data-label="No.">{index+1}</td><td data-label="Category"><div className="category-name">{item.thumbnail_url&&<img src={`${item.thumbnail_url}?v=${encodeURIComponent(item.updated_at)}`} alt="" onError={event=>{event.currentTarget.style.display="none";const fallback=event.currentTarget.nextElementSibling as HTMLElement|null;if(fallback)fallback.style.display="grid";}}/>}<span style={item.thumbnail_url?{display:"none"}:undefined}>{item.name[0].toUpperCase()}</span><strong>{item.name}</strong></div></td>{level==="L2"&&<td data-label="Main Category"><span className="parent-category-pill">{item.parent_name}</span></td>}<td data-label="Products">{item.product_count}</td><td data-label="Priority">{item.priority}</td><td data-label="Updated">{new Date(item.updated_at).toLocaleDateString()}</td><td data-label="Actions"><div className="row-actions"><button className="row-action edit" onClick={()=>onEdit(item)}>Edit</button><button className="row-action delete" onClick={()=>onDelete(item)}>Delete</button></div></td></tr>)}</tbody></table></div></section>;
}

export default function CategoryList({categories,loading,search,onSearchChange,onAdd,onEdit,onDelete}:Props){
 const [activeLevel,setActiveLevel]=useState<"L1"|"L2">("L1");
 const l1=categories.filter(item=>!item.parent_id).sort((a,b)=>a.priority-b.priority||a.name.localeCompare(b.name));
 const l2=categories.filter(item=>item.parent_id).sort((a,b)=>(a.parent_name||"").localeCompare(b.parent_name||"")||a.priority-b.priority||a.name.localeCompare(b.name));
 return <div className="category-page"><section className="category-title-card"><h1>All Categories</h1><div className="category-header-tools"><label className="category-search"><span>⌕</span><input value={search} onChange={e=>onSearchChange(e.target.value)} placeholder={`Search ${activeLevel} categories`}/></label><button className="primary-button category-add" onClick={onAdd}>＋ Add Category</button></div></section><nav className="category-level-switch" aria-label="Category level"><button className={activeLevel==="L1"?"active":""} onClick={()=>setActiveLevel("L1")}><span>L1</span><div><strong>Main Categories</strong></div><b>{l1.length}</b></button><button className={activeLevel==="L2"?"active":""} onClick={()=>setActiveLevel("L2")}><span>L2</span><div><strong>Subcategories</strong></div><b>{l2.length}</b></button></nav><div className="category-single-table">{activeLevel==="L1"?<CategoryTable title="L1 Main Categories" items={l1} level="L1" loading={loading} onEdit={onEdit} onDelete={onDelete}/>:<CategoryTable title="L2 Subcategories" items={l2} level="L2" loading={loading} onEdit={onEdit} onDelete={onDelete}/>}</div></div>;
}
