"use client";
import {FormEvent,useState} from "react";
import type {Category,CategoryInput} from "./types";
type Props={categories:Category[];initial:Category|null;saving:boolean;onCancel:()=>void;onSave:(payload:CategoryInput,image:File|null)=>Promise<void>};
export default function CategoryForm({categories,initial,saving,onCancel,onSave}:Props){
 const [level,setLevel]=useState<"l1"|"l2">(initial?.parent_id?"l2":"l1"),[name,setName]=useState(initial?.name||""),[parentId,setParentId]=useState(initial?.parent_id||""),[description,setDescription]=useState(initial?.description||""),[priority,setPriority]=useState(initial?.priority||0),[image,setImage]=useState<File|null>(null),[error,setError]=useState("");
 const mains=categories.filter(item=>!item.parent_id&&item.id!==initial?.id);
 const submit=async(event:FormEvent)=>{event.preventDefault();if(name.trim().length<2)return setError("Category name must contain at least 2 characters.");if(level==="l2"&&!parentId)return setError("Select an L1 main category.");setError("");await onSave({name:name.trim(),description:description.trim()||null,parent_id:level==="l2"?parentId:null,brands:[],priority,thumbnail_url:initial?.thumbnail_url||null,meta_title:null,meta_description:null,meta_image_url:null},image)};
 return <div className="category-page"><section className="category-title-card form-title"><h1>{initial?"Edit Category":"Add Category"}</h1><button className="secondary-button" onClick={onCancel}>Back</button></section><form className="category-compact-form" onSubmit={submit}><section className="form-card"><h2>Category Information</h2><div className="category-level-picker"><button type="button" className={level==="l1"?"active":""} onClick={()=>{setLevel("l1");setParentId("")}}><strong>L1</strong><span>Main Category</span></button><button type="button" className={level==="l2"?"active":""} onClick={()=>setLevel("l2")}><strong>L2</strong><span>Subcategory</span></button></div>{level==="l2"&&<div className="field"><label>L1 Main Category *</label><select value={parentId} onChange={event=>setParentId(event.target.value)}><option value="">Select main category</option>{mains.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></div>}<div className="field"><label>Category Name *</label><input value={name} onChange={event=>setName(event.target.value)}/></div><div className="field"><label>Description</label><textarea rows={3} value={description} onChange={event=>setDescription(event.target.value)}/></div><div className="field"><label>Sorting Priority</label><input type="number" min="0" max="9999" value={priority} onChange={event=>setPriority(Number(event.target.value))}/></div><label className="catalog-image-picker"><input type="file" accept="image/webp,image/jpeg,image/png" onChange={event=>setImage(event.target.files?.[0]||null)}/><strong>{image?image.name:initial?.thumbnail_url?"Replace Category Image":"Upload Category Image"}</strong><small>WEBP, JPG or PNG · maximum 8 MB</small></label>{error&&<div className="form-error">{error}</div>}<div className="form-actions"><button type="button" className="secondary-button" onClick={onCancel}>Cancel</button><button className="primary-button" disabled={saving}>{saving?"Saving...":initial?"Update Category":"Save Category"}</button></div></section><aside className="form-steps"><h3>Category Level</h3><div className={`step ${level==="l1"?"active":""}`}><i>1</i><span>L1 Main Category</span></div><div className={`step ${level==="l2"?"active":""}`}><i>2</i><span>L2 Subcategory</span></div></aside></form></div>;
}
